In [1]:
import numpy as np

In [2]:
arr1 = np.array([5, 17, 3, 26, 31])
arr2 = np.zeros(2)
np.concatenate([arr1, arr2])

array([ 5., 17.,  3., 26., 31.,  0.,  0.])

In [3]:
arr3 = np.ones(3)
np.concatenate([arr1, arr2, arr3])

array([ 5., 17.,  3., 26., 31.,  0.,  0.,  1.,  1.,  1.])

In [4]:
list1 = [5, 17, 3, 26, 31]
sorted_list1 = sorted(list1)
print(sorted_list1)

[3, 5, 17, 26, 31]


In [5]:
list1.sort()
print(list1)

[3, 5, 17, 26, 31]


In [6]:
print(np.sort(arr1))
print(arr1)

[ 3  5 17 26 31]
[ 5 17  3 26 31]


In [7]:
print(arr1.sort())
print(arr1)

None
[ 3  5 17 26 31]


In [8]:
arr1[0]

3

In [9]:
arr1[-2]

26

In [10]:
arr1[1:4]

array([ 5, 17, 26])

In [13]:
arr4 = np.array([6, 7, 8, 9, 10])
arr5 = np.ones(5)
print(arr4 + arr5)
print(arr4 - arr5)
print(arr4 * arr5)
print(arr4 / arr5)

[ 7.  8.  9. 10. 11.]
[5. 6. 7. 8. 9.]
[ 6.  7.  8.  9. 10.]
[ 6.  7.  8.  9. 10.]


In [14]:
arr4 * 3

array([18, 21, 24, 27, 30])

In [15]:
print(arr4.max())
print(arr4.min())
print(arr4.sum())
print(arr4.mean())

10
6
40
8.0


In [18]:
arr = np.array([-22, 3, 65, 9, 11, 7])
print(arr > 6)
print(arr)

[False False  True  True  True  True]
[-22   3  65   9  11   7]
